name: cicd-pipeline
on: [push]

env:
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  nx:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: docker login
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: install podman
        uses: gacts/install-podman@v1.1.0
        with:
          kind: stable
          qemu: true

      - name: build image
        run: ./nx/build.sh
        shell: bash
        env:
          CONTAINER_REGISTRY: docker.io/${{ env.REGISTRY_USER }}
